fragment_directory: changelog.d

tag-prefix: v

categories:
  - name: 💥 Breaking Changes
    bump: major
    label: major
  - name: 🚀 Enhancements and New Features
    bump: minor
    label: minor
  - name: 🐛 Bug Fixes
    label: patch
  - name: 🔩 Dependencies
    label: dependencies
  - name: 📝 Documentation
    label: documentation
  - name: 🏠 Internal
    label: internal
  - name: 🏎 Performance
    label: performance
  - name: 🧪 Tests
    label: tests
