name: Add changelog snippet

inputs:
  git-author-name:
    default: "DataLad Bot"
  git-author-email:
    default: "bot@datalad.org"
  token:
    required: true
  config:
    default: ".datalad-release-action.yaml"
  rm-labels:
    default: ""

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '^3.7'

    - name: Generate or rename changelog snippet
      # We can't use nox or tox, as those change the working dir to the folder
      # containing the nox/tox-file, yet we need to remain in the same
      # directory in which the action was invoked.
      run: |
        set -ex
        python -m venv "$GITHUB_ACTION_PATH"/venv
        source "$GITHUB_ACTION_PATH"/venv/bin/activate
        pip install -r "$GITHUB_ACTION_PATH"/../requirements.txt
        PYTHONPATH="$PYTHONPATH":"$GITHUB_ACTION_PATH"/.. \
          python -m datalad_release_action \
          -c "$config" \
          ${{ github.repository }} \
          add-changelog-snippet \
          ${{ github.event.pull_request.number }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GIT_AUTHOR_NAME: ${{ inputs.git-author-name }}
        GIT_AUTHOR_EMAIL: ${{ inputs.git-author-email }}
        GIT_COMMITTER_NAME: ${{ inputs.git-author-name }}
        GIT_COMMITTER_EMAIL: ${{ inputs.git-author-email }}
        config: ${{ inputs.config }}

    - name: Remove labels
      if: inputs.rm-labels != ''
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: ${{ inputs.rm-labels }}

    - name: Push
      run: git push origin HEAD:${{ github.head_ref }}
      shell: bash

# vim:set et sts=2:
